services:
  # Backend Service
  - type: web
    name: trilion-backend
    env: node
    buildCommand: |
      npm install && cd server && npm install
      echo "Installing Python dependencies (optional)..."
      pip install --upgrade pip setuptools wheel 2>/dev/null || echo "pip not available, skipping Python setup"
      cd server && pip install -r requirements-render.txt 2>/dev/null || echo "Python dependencies optional - continuing with Node.js"
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://trilion-frontend.onrender.com

  # Frontend Service
  - type: web
    name: trilion-frontend
    env: static
    buildCommand: npm run build:frontend
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://trilion-backend.onrender.com 