services:
  - type: web
    name: trilion-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://trilion-backend.onrender.com 